import type { Metadata } from "next";
import { PageHero, SiteFooter, SiteHeader } from "../site-shell";
export const metadata: Metadata = { title: "About JOZING | Ceramic Tableware Supplier", description: "JOZING ready-stock ceramic tableware supply and OEM/ODM support in Chaozhou, China." };
export default function AboutPage() { return <main><SiteHeader />
  <PageHero eyebrow="ABOUT JOZING" title="Flexible supply, grounded in ceramics." intro="JOZING supports global importers, wholesalers and brands through two practical sourcing paths: value-driven ready stock and tailored OEM/ODM ceramic tableware manufacturing." />
  <section className="story shell"><div className="story-copy"><p className="eyebrow">CHAOZHOU · CHINA</p><h2>Built around the way B2B buyers actually source.</h2><p>Some buyers need available stock and competitive container value. Others need a distinctive collection built around their market. We keep these needs separate, then help each buyer move through the right sourcing process.</p><p>Our 6,000 m² factory and warehouse supports ceramic tableware supply, stock handling, product coordination and export preparation. Availability, packing and commercial terms are confirmed against the current lot or project before quotation.</p></div><figure className="story-photo"><img src="/factory/01-real-jozing-warehouse.webp" alt="JOZING ceramic tableware warehouse in Chaozhou"/><figcaption>JOZING warehouse · Real site photo</figcaption></figure></section>
  <section className="page-band"><div className="shell fact-row"><div><strong>6,000 m²</strong><span>Factory & warehouse</span></div><div><strong>2 supply paths</strong><span>Ready stock + OEM/ODM</span></div><div><strong>Global</strong><span>Export market support</span></div></div></section>
  <section className="dual-path shell"><article><span>01</span><p className="eyebrow">READY STOCK</p><h2>Buy what is available.</h2><p>Clearance and inventory ceramic tableware can be discussed by carton, pallet, ton or container. Ask for the current list, packing details, available quantity and loading plan.</p><a href="/contact">Request current stock →</a></article><article><span>02</span><p className="eyebrow">OEM / ODM</p><h2>Build what your market needs.</h2><p>Share a reference image, shape, glaze, decoration, logo or packaging brief. We coordinate development and sampling through production and export packing.</p><a href="/contact">Discuss a custom project →</a></article></section>
  <section className="values"><div className="shell"><p className="eyebrow">HOW WE WORK</p><h2>Clear information before commitment.</h2><div className="value-grid"><article><b>01</b><h3>Confirm the requirement</h3><p>Product, quantity, market, target price, packing and destination.</p></article><article><b>02</b><h3>Match the supply path</h3><p>Current stock opportunity, mixed loading or an OEM/ODM project.</p></article><article><b>03</b><h3>Prepare the offer</h3><p>Specifications, terms and availability confirmed for the inquiry.</p></article><article><b>04</b><h3>Coordinate delivery</h3><p>Production or stock preparation, inspection support, packing and shipment planning.</p></article></div></div></section>
  <section className="page-cta"><div className="shell"><p className="eyebrow">START A CONVERSATION</p><h2>Tell us what you are sourcing.</h2><div><a className="btn primary" href="/contact">Contact JOZING</a><a className="btn text" href="/faq">Read buyer FAQ →</a></div></div></section><SiteFooter /></main>; }
