import type { Metadata } from "next";
import { PageHero, SiteFooter, SiteHeader } from "../site-shell";
export const metadata: Metadata = { title: "About JOZING | Ceramic Tableware Manufacturer & Stock Supplier", description: "With ceramic tableware experience since 2003, JOZING supports global B2B buyers with ready-stock ceramic tableware and OEM/ODM manufacturing from Chaozhou, China.", alternates:{canonical:"https://www.jozing.cn/about/"} };
export default function AboutPage() { return <main><SiteHeader />
  <PageHero eyebrow="ABOUT JOZING · SINCE 2003" title="Flexible supply, grounded in ceramics." intro="Xiamen Jozing Industrial Co., Ltd. supports global importers, wholesalers and brands through two practical sourcing paths: value-driven ready stock and tailored OEM/ODM ceramic tableware manufacturing." />
  <section className="story shell"><div className="story-copy"><p className="eyebrow">CHAOZHOU · GUANGDONG · CHINA</p><h2>Built around the way B2B buyers actually source.</h2><p>JOZING's ceramic tableware experience dates back to 2003; Xiamen Jozing Industrial Co., Ltd. was established in 2017 to serve global B2B buyers. We supply ceramic tableware to importers, wholesalers, hospitality suppliers and brands. Some buyers need available stock and competitive container value; others need a repeatable collection built around their market.</p><p>Our 6,000 m² factory and warehouse supports stock handling, ceramic product coordination, inspection support and export preparation. Availability, packing, compliance scope and commercial terms are confirmed against the actual lot or OEM/ODM project before quotation.</p><p><strong>Company:</strong> Xiamen Jozing Industrial Co., Ltd.<br/><strong>Sales:</strong> sales@jozing.cn · +86 152 8018 6517<br/><strong>Warehouse:</strong> No. 3, Gubantou Village, Chao&apos;an District, Chaozhou, Guangdong, China</p></div><figure className="story-photo"><img src="/factory/01-real-jozing-warehouse.webp" alt="JOZING ceramic tableware warehouse in Chaozhou"/><figcaption>JOZING warehouse · Real site photo</figcaption></figure></section>
  <section className="client-proof"><div className="shell"><div className="client-proof-head"><div><p className="eyebrow">SELECTED CLIENT COOPERATION</p><h2>Trusted across international retail and tableware markets.</h2></div><p>JOZING has supported brands and professional buyers through ceramic sourcing, ready-stock supply, custom manufacturing and export coordination.</p></div><figure><img src="/jozing-selected-client-brands.png" width="1525" height="430" loading="lazy" alt="Selected customer and brand cooperation references supplied by JOZING"/><figcaption>Selected cooperation references supplied by JOZING. All logos remain the property of their respective owners; their display does not imply endorsement or an ongoing exclusive relationship.</figcaption></figure></div></section>
  <section className="page-band"><div className="shell fact-row"><div><strong>Since 2003</strong><span>Ceramic tableware experience</span></div><div><strong>6,000 m²</strong><span>Factory & warehouse</span></div><div><strong>2 supply paths</strong><span>Ready stock + OEM/ODM</span></div></div></section>
  <section className="dual-path shell"><article><span>01</span><p className="eyebrow">READY STOCK</p><h2>Buy what is available.</h2><p>Clearance and inventory ceramic tableware can be discussed by carton, pallet, ton or container. Ask for the current list, packing details, available quantity and loading plan.</p><a href="/contact">Request current stock →</a></article><article><span>02</span><p className="eyebrow">OEM / ODM</p><h2>Build what your market needs.</h2><p>Share a reference image, shape, glaze, decoration, logo or packaging brief. We coordinate development and sampling through production and export packing.</p><a href="/contact">Discuss a custom project →</a></article></section>
  <section className="values"><div className="shell"><p className="eyebrow">HOW WE WORK</p><h2>Clear information before commitment.</h2><div className="value-grid"><article><b>01</b><h3>Confirm the requirement</h3><p>Product, quantity, market, target price, packing and destination.</p></article><article><b>02</b><h3>Match the supply path</h3><p>Current stock opportunity, mixed loading or an OEM/ODM project.</p></article><article><b>03</b><h3>Prepare the offer</h3><p>Specifications, terms and availability confirmed for the inquiry.</p></article><article><b>04</b><h3>Coordinate delivery</h3><p>Production or stock preparation, inspection support, packing and shipment planning.</p></article></div></div></section>
  <section className="page-cta"><div className="shell"><p className="eyebrow">START A CONVERSATION</p><h2>Tell us what you are sourcing.</h2><div><a className="btn primary" href="/contact">Contact JOZING</a><a className="btn text" href="/supplier-profile/">Verify supplier facts →</a><a className="btn text" href="/faq">Read buyer FAQ →</a></div></div></section><SiteFooter /></main>; }
