export type Guide = { slug: string; title: string; description: string; updated: string; readTime: string; sections: { heading: string; paragraphs: string[]; bullets?: string[] }[] };

export const guides: Guide[] = [
  { slug: "buy-ceramic-tableware-by-ton-from-china", title: "How to Buy Ceramic Tableware by the Ton from China", description: "A practical guide to pricing units, mixed lots, packing lists, inspection and container planning for ceramic stock purchases.", updated: "2026-08-25", readTime: "8 min", sections: [
    { heading: "What buying by the ton means", paragraphs: ["Ton-based ceramic offers usually refer to the net or gross weight of a mixed or defined stock lot, not a fixed retail set. Before comparing prices, ask whether the quoted weight includes cartons and protective materials."], bullets: ["Confirm net versus gross weight", "Request the assortment and condition breakdown", "Ask whether replacements or second-quality pieces are included"] },
    { heading: "The documents to request", paragraphs: ["A useful quotation should connect price, weight and loading data. Ask for a dated packing list rather than relying only on showroom photographs."], bullets: ["SKU or assortment list", "Pieces per carton and carton count", "Gross weight, dimensions and CBM", "Available quantity and validity date"] },
    { heading: "How JOZING prepares an offer", paragraphs: ["JOZING first confirms the target market, product mix and destination port, then checks current availability and prepares the commercial offer around the actual lot. Buyers can request inspection support before shipment."] }
  ]},
  { slug: "ceramic-stock-lots-vs-regular-production", title: "Ceramic Stock Lots vs. Regular Production Orders", description: "Choose between ready stock, production surplus and OEM manufacturing based on speed, consistency, MOQ and repeatability.", updated: "2026-08-25", readTime: "7 min", sections: [
    { heading: "When ready stock is the better fit", paragraphs: ["Ready stock suits buyers prioritizing speed, lower entry cost or opportunistic assortments. The trade-off is that colors, shapes and quantities may not be repeatable after the lot is sold."], bullets: ["Faster shipment", "Competitive clearance pricing", "Mixed loading opportunities"] },
    { heading: "When regular production is safer", paragraphs: ["Regular production is better when a collection must be reordered, branded or controlled against an approved sample. Lead time is longer and MOQ is normally higher, but specifications are more repeatable."] },
    { heading: "Use a two-path sourcing plan", paragraphs: ["Many importers use stock lots for promotional or fast-moving opportunities and OEM/ODM for their core repeatable range. JOZING keeps these two supply paths clearly separated in quotations."] }
  ]},
  { slug: "ceramic-container-loading-guide", title: "Ceramic Tableware Container Loading Guide", description: "Understand carton quantity, CBM, payload and mixed-container planning before confirming a ceramic order.", updated: "2026-08-25", readTime: "8 min", sections: [
    { heading: "Weight and volume both matter", paragraphs: ["Ceramic tableware is dense, but protective packaging adds volume. A container may reach the safe payload before all cubic capacity is used, especially with heavy plates and bowls."], bullets: ["Check carrier payload limits", "Use final carton dimensions", "Reserve space for safe loading and bracing"] },
    { heading: "Mixed loading needs a carton-level plan", paragraphs: ["For a mixed container, calculate cartons, pieces, gross weight and CBM for every SKU. This lets the buyer adjust the mix before warehouse preparation begins."] },
    { heading: "Reduce breakage risk", paragraphs: ["Keep heavier cartons lower, avoid unsupported gaps and use suitable dividers, foam or paper protection. Confirm whether pallets are required because they change both capacity and handling."] }
  ]},
  { slug: "ceramic-tableware-quality-inspection-checklist", title: "Ceramic Tableware Quality Inspection Checklist", description: "A buyer-focused checklist covering glaze, decoration, dimensions, wobble, chips, packing and compliance documents.", updated: "2026-08-25", readTime: "9 min", sections: [
    { heading: "Visual and functional checks", paragraphs: ["Inspection criteria should distinguish normal handmade or kiln variation from unacceptable defects. Define the standard before inspection rather than after goods are packed."], bullets: ["Cracks, chips and sharp edges", "Glaze pinholes, crawling and contamination", "Decoration position and color tolerance", "Flatness, wobble and handle attachment"] },
    { heading: "Specification checks", paragraphs: ["Measure representative samples for diameter, height, capacity and weight. For sets, verify fit, stacking and assortment ratios."] },
    { heading: "Packing and documentation", paragraphs: ["Check inner protection, carton strength, shipping marks and quantity. Required food-contact or market compliance documents should be agreed for the destination before order confirmation."] }
  ]},
  { slug: "oem-ceramic-dinnerware-moq-sampling-lead-time", title: "OEM Ceramic Dinnerware: MOQ, Sampling and Lead Time", description: "Plan a custom ceramic collection from reference image and sample approval through production, inspection and export packing.", updated: "2026-08-25", readTime: "8 min", sections: [
    { heading: "MOQ depends on the customization depth", paragraphs: ["A logo or decal on an existing shape normally requires less development than a new mold, glaze system or packaging program. Share the target quantity early so the supplier can recommend a realistic route."] },
    { heading: "A practical sampling sequence", paragraphs: ["Start with a written brief covering shape, material, size, glaze, decoration and packaging. Review one approval sample or a controlled sample set before bulk production."], bullets: ["Reference and specification review", "Sample quotation and timing", "Sample evaluation and corrections", "Signed or documented approval"] },
    { heading: "Build time for control, not only production", paragraphs: ["The schedule should include sample revisions, material preparation, firing, decoration, inspection and packing. Seasonal capacity and public holidays should be considered before setting the delivery date."] }
  ]},
  { slug: "ceramic-tableware-compliance-coc-rohs-food-contact", title: "Ceramic Tableware Compliance: COC, RoHS and Food-Contact Documents", description: "Clarify destination requirements and avoid treating different ceramic compliance documents as interchangeable.", updated: "2026-08-25", readTime: "8 min", sections: [
    { heading: "Start with the destination market", paragraphs: ["Document requirements differ by country, buyer and intended use. A certificate of conformity, food-contact test report and restricted-substance requirement serve different purposes and should not be treated as the same document."] },
    { heading: "Confirm the exact product and test scope", paragraphs: ["A report should match the material, glaze, decoration and product family being shipped. Ask which laboratory, test method, sample and validity period apply."], bullets: ["Product and material covered", "Applicable standard or regulation", "Laboratory and report number", "Issue date and buyer acceptance"] },
    { heading: "JOZING compliance support", paragraphs: ["JOZING can discuss COC, RoHS and destination-specific compliance support during quotation. Final requirements, testing scope, costs and documents must be confirmed for the actual order and market."] }
  ]}
];
